export const MASTER_TASKS = {
  COLLEGES: [
    "Research colleges by your intended/chosen major.",
    "Compare two colleges on your Colleges List.",
    "Compare tuition and fees at three colleges on your Colleges List.",
    "Research graduation rates at all of the colleges on your Colleges List.",
    "Research freshman retention at all of the colleges on your Colleges List.",
    "Compare campus sizes for 4 of the colleges on your Colleges List.",
    "Explore student organizations at 5 of the colleges on your Colleges List.",
    "Watch virtual campus tours at all of the colleges on your Colleges List.",
    "Research housing options at all of the colleges on your Colleges List.",
    "Learn about honors programs at all of the colleges on your Colleges List.",
    "Review admissions requirements at all of the colleges on your Colleges List.",
    "Research early action/early decision and the differences between the two.",
    "Compare financial aid offered by all of the colleges on your Colleges List.",
    "Compare study abroad opportunities at all of the colleges on your Colleges List.",
    "Contact admissions representatives at all of the colleges on your Colleges List to introduce yourself.",
    "Create your Common App/Black Common App account.",
    "Complete your Common App/Black Common App student profile.",
    "Add colleges to your application list on the Common App/Black Common App.",
    "Track application deadlines for all of the colleges on your Colleges List.",
    "Request transcripts from your Guidance Counselor.",
    "Request recommendation letters from 1 guidance counselor, 2 teachers, 1 supervisor/community service leader.",
    "Upload required documents to your Schoolari account.",
    "Submit college applications.",
    "Verify submission confirmations.",
    "Track admission decisions.",
    "Schedule a campus tour for at least 2 of the colleges on your Colleges List.",
    "Attend a virtual tour at all of the colleges on your Colleges List.",
    "Prepare questions before any campus visits.",
    "Meet an admissions counselor at one of the colleges on your Colleges List.",
    "Visit your intended academic department and introduce yourself to a Dean or Professor.",
    "Talk with current college students about the college and adjusting to college life.",
    "Visit residence halls.",
    "Compare campuses that you have visited.",
    "Take notes after your visit.",
    "Collect contact information for at least one Dean, one professor, admissions director and financial aid director.",
    "Practice 25 Math questions.",
    "Practice 25 Reading questions.",
    "Practice 25 English questions.",
    "Complete a timed practice section.",
    "Review missed questions.",
    "Learn at least 25 new vocabulary words.",
    "Watch SAT/ACT strategy videos.",
    "Register for an exam.",
    "Set a target score.",
    "Review score reports.",
    "Create your FSA ID.",
    "Learn FAFSA deadlines.",
    "Research grants.",
    "Understand work-study and how it works at colleges.",
    "Compare financial aid packages.",
    "Learn about student loans, interest rates and repayments.",
    "Calculate how much you will have to pay back for a $50,000 student loan.",
    "Calculate full cost of attendance (COA) at the colleges on your Colleges List.",
    "Learn about merit aid.",
    "Research institutional aid.",
    "Understand scholarship renewal requirements."
  ],
  SCHOLARSHIPS: [
    "Search scholarships by major.",
    "Search scholarships by GPA.",
    "Search scholarships by ethnicity.",
    "Search scholarships by community service.",
    "Search scholarships by extracurricular activities.",
    "Search scholarships by state.",
    "Search scholarships local scholarships.",
    "Search scholarships employer scholarships.",
    "Search scholarships civic organization scholarships.",
    "Search scholarships offered by colleges on your Colleges List.",
    "Add more scholarships to your 'I Will Apply' list.",
    "Verify eligibility of scholarships on your 'I Will Apply' list.",
    "Organize scholarships by deadline.",
    "Organize scholarships by award amount.",
    "Set deadline reminders.",
    "Remove expired scholarships.",
    "Update your tracker.",
    "Prioritize applications.",
    "Create a scholarship calendar.",
    "Monitor application status.",
    "Designate one day each week for your 'Scholarship Day' to search and apply.",
    "Apply for 10 scholarships.",
    "Submit required documents.",
    "Confirm receipt.",
    "Follow up with scholarship organizations.",
    "Complete three local scholarships.",
    "Complete three national scholarships.",
    "Complete three college scholarships.",
    "Review submission confirmations.",
    "Update your application tracker.",
    "Record award notifications.",
    "Join scholarship organizations.",
    "Attend scholarship webinars.",
    "Connect with scholarship providers.",
    "Follow scholarship foundations.",
    "Build mentor relationships.",
    "Learn about scholarship opportunities through community organizations."
  ],
  ESSAYS: [
    "List 3 meaningful life experiences.",
    "Identify your leadership experiences.",
    "Reflect on challenges you have overcome.",
    "List your volunteer experiences.",
    "List your academic accomplishments.",
    "Identify your career goals.",
    "Identify people who influenced you.",
    "Reflect on your personal growth.",
    "Brainstorm essay topics.",
    "Match stories to essay prompts.",
    "Write your essay introduction.",
    "Write your essay conclusion.",
    "Draft your first essay.",
    "Expand supporting details in your essay.",
    "Improve your storytelling in your essay.",
    "Add vivid examples to your essay.",
    "Strengthen transitions in your essay.",
    "Draft scholarship essays.",
    "Draft supplemental essays.",
    "Draft Common App/Black Common App essays.",
    "Improve sentence flow in your essay.",
    "Reduce word count in one of your essays.",
    "Remove repetition in your essay.",
    "Strengthen opening paragraph in your essay.",
    "Strengthen closing paragraph in your essay.",
    "Improve clarity in your essays.",
    "Improve grammar in your essays.",
    "Read your essays aloud.",
    "Rewrite weak sections in your essays.",
    "Upload updated versions to your Schoolari Document Vault.",
    "Have a teacher review your essays.",
    "Have a parent review your essays.",
    "Have a mentor review your essays.",
    "Compare multiple drafts of your essays.",
    "Incorporate feedback from your essay reviewers.",
    "Final proofread of your essays.",
    "Final formatting of your essays.",
    "Submit final essay.",
    "Save final version to your Schoolari Document Vault."
  ],
  JOBS: [
    "Add leadership positions to your resume.",
    "Add volunteer hours to your resume.",
    "Add employment history to your resume.",
    "Add internships to your resume.",
    "Add awards to your resume.",
    "Add honors to your resume.",
    "Add certifications to your resume.",
    "Add dual enrollment courses to your resume.",
    "Add GPA to your resume.",
    "Upload your latest resume to your Schoolari Document Vault.",
    "Research two different career paths related to your intended major.",
    "Compare careers in your intended field.",
    "Research salary information for your intended career path.",
    "Research education requirements for your intended career path.",
    "Research certifications for your intended career path.",
    "Interview a professional currently in your career path.",
    "Shadow a professional in your career path.",
    "Research industry growth in your career industry.",
    "Explore apprenticeships.",
    "Learn about entrepreneurship and how you can own your own business in your intended career field.",
    "Search internship opportunities in your intended career field.",
    "Search summer jobs in your intended career field.",
    "Search volunteer opportunities related to your career path.",
    "Apply for an internship.",
    "Apply for a summer job.",
    "Research companies in your intended career industry.",
    "Attend a career fair.",
    "Prepare job references.",
    "Follow up on applications.",
    "Track application status.",
    "Join a student organization.",
    "Attend club meetings.",
    "Run for leadership.",
    "Organize a service project.",
    "Mentor another student.",
    "Participate in competitions.",
    "Document leadership experiences.",
    "Track community service hours.",
    "Plan a volunteer activity.",
    "Build your leadership portfolio.",
    "Create a LinkedIn profile.",
    "Connect with a professional.",
    "Conduct an informational interview with someone in your intended career path.",
    "Join a professional organization.",
    "Attend a networking event.",
    "Attend a webinar.",
    "Research mentors.",
    "Follow universities and employers.",
    "Send thank-you messages.",
    "Build your professional network."
  ]
};
